### ISSUE TITLE
The script no longer works on Python < 2.6

### ISSUE THREAD

**Issue by markvl** [djl/vcprompt#31]
Changeset 24c1c700dfd9d574e9d1994b92448f8e9f44cc70 introduced the following code:

```
os.path.relpath(...)
```

But `os.path.relpath` is only available since Python version 2.6 according to [the documentation](http://docs.python.org/2/library/os.path.html#os.path.relpath). 

Is it possible to change the code to be compatible with Python 2.5 and 2.4, e.g. using code similar to what can be found in [hg-tools](https://bitbucket.org/lindenlab/hg-tools/src/b42c98464e90/relpath/relpath.py) or [this blog post](http://www.saltycrane.com/blog/2010/03/ospathrelpath-source-code-python-25/)/[BareNecessitites](http://jimmyg.org/work/code/barenecessities/0.2.5/manual.html#the-relpath-function)?

Or should the README just be updated to state that you need at least Python 2.6?

**Comment by djl** [comment]
Ack! I thought the tests would have caught something like this. I'll need to look into exactly why they didn't :(

I've added a `relpath` function (lifted pretty much wholesale from Python2.7's `posixpath`) in 3bb9eec7fe65ca9d78a07d8d3df8f3ffa8dbcfde and really confirmed that it's working:

```
$ python2.4 ./vcprompt -f '%P'
vcprompt
```

> Or should the README just be updated to state that you need at least Python 2.6?

At some point I'd like to drop support for Python 2.4 (just because ehhh) but since it's fairly trivial to support I don't really see any reason to do right now.

**Comment by markvl** [comment]
Thanks for the quick response and the fix!
